//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream malfound {
            get {
                return ResourceManager.GetStream("malfound", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream ready {
            get {
                return ResourceManager.GetStream("ready", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_0 {
            get {
                return ResourceManager.GetStream("sound_0", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_1 {
            get {
                return ResourceManager.GetStream("sound_1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_10 {
            get {
                return ResourceManager.GetStream("sound_10", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_2 {
            get {
                return ResourceManager.GetStream("sound_2", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_3 {
            get {
                return ResourceManager.GetStream("sound_3", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_4 {
            get {
                return ResourceManager.GetStream("sound_4", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_5 {
            get {
                return ResourceManager.GetStream("sound_5", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_6 {
            get {
                return ResourceManager.GetStream("sound_6", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_7 {
            get {
                return ResourceManager.GetStream("sound_7", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_8 {
            get {
                return ResourceManager.GetStream("sound_8", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_9 {
            get {
                return ResourceManager.GetStream("sound_9", resourceCulture);
            }
        }
    }
}
